import os
import environ
from datetime import datetime
from django.conf import settings
from django.core.mail import EmailMessage
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from .models import SecurityLog
from celery import shared_task

env = environ.Env()

@shared_task
def log_security_event(user_id, action, resource, reason, ip_address=None):
    SecurityLog.objects.create(
        user_id=user_id,
        action=action,
        resource=resource,
        reason=reason,
        ip_address=ip_address
    )
    return f"Security event {action} recorded for user {user_id}"

@shared_task
def generate_security_report():
    folder_path = os.path.join(settings.MEDIA_ROOT, 'reports')
    os.makedirs(folder_path, exist_ok=True)
    
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_path = os.path.join(folder_path, f'security_audit_{timestamp_str}.pdf')
    
    doc = SimpleDocTemplate(
        file_path, 
        pagesize=letter, 
        rightMargin=30, 
        leftMargin=30, 
        topMargin=40, 
        bottomMargin=30
    )
    elements = []
    styles = getSampleStyleSheet()

    header_style = ParagraphStyle(
        'HeaderStyle',
        parent=styles['Title'],
        fontSize=22,
        textColor=colors.HexColor("#1A237E"),
        alignment=0,
        spaceAfter=10
    )
    
    sub_style = ParagraphStyle(
        'SubStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.grey,
        spaceAfter=25
    )

    cell_style = ParagraphStyle('CellStyle', parent=styles['Normal'], fontSize=8, leading=11)

    elements.append(Paragraph("ARGUS SECURITY AUDIT", header_style))
    elements.append(Paragraph(f"System Generated Report • {datetime.now().strftime('%B %d, %Y')}", sub_style))
    elements.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1A237E"), spaceAfter=20))

    logs = SecurityLog.objects.all().order_by('-timestamp')
    data = [["TIMESTAMP", "USER", "ACTION", "REASON", "IP ADDRESS"]]
    
    for log in logs:
        data.append([
            log.timestamp.strftime('%Y-%m-%d\n%H:%M'),
            str(log.user.username if log.user else "SYSTEM").upper(),
            str(log.action).replace("_", " "),
            Paragraph(str(log.reason), cell_style),
            str(log.ip_address if log.ip_address else "—")
        ])

    col_widths = [1.1*inch, 1.3*inch, 1.5*inch, 2.6*inch, 1.0*inch]
    table = Table(data, colWidths=col_widths, repeatRows=1)

    style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#F5F7F9")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#1A237E")),
        ('ALIGN', (0, 0), (-1, 0), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('TOPPADDING', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('VALIGN', (0, 1), (-1, -1), 'TOP'),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 10),
        ('TOPPADDING', (0, 1), (-1, -1), 10),
        ('LINEBELOW', (0, 0), (-1, 0), 1.5, colors.HexColor("#1A237E")),
        ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.HexColor("#E0E0E0")),
    ])

    for i, row in enumerate(data):
        if i == 0: continue
        action_text = str(row[2]).upper()
        if any(word in action_text for word in ["DENIED", "VIOLATION", "UNAUTHORIZED"]):
            style.add('TEXTCOLOR', (2, i), (2, i), colors.HexColor("#C62828"))
            style.add('FONTNAME', (2, i), (2, i), 'Helvetica-Bold')

    table.setStyle(style)
    elements.append(table)
    
    elements.append(Spacer(1, 0.5 * inch))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.grey))
    elements.append(Paragraph("CONFIDENTIAL • PROPERTY OF ARGUS SECURITY SYSTEMS", styles['Italic']))

    doc.build(elements)

    admin_email = env('ADMIN_EMAIL')
    subject = f"Argus Audit Report: {datetime.now().strftime('%Y-%m-%d')}"
    body = "Please find the attached daily security audit report generated by the Argus System."
    
    email = EmailMessage(
        subject,
        body,
        settings.DEFAULT_FROM_EMAIL,
        [admin_email],
    )
    email.attach_file(file_path)
    email.send(fail_silently=False)

    return f"Report generated and sent to {admin_email}"