# Generated by Django 6.0.2 on 2026-02-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_department', models.CharField(choices=[('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('ENGINEERING', 'Engineering'), ('MARKETING', 'Marketing')], max_length=100)),
                ('required_clearance', models.IntegerField(default=1)),
                ('start_time', models.TimeField(default='09:00:00')),
                ('end_time', models.TimeField(default='17:00:00')),
            ],
        ),
    ]
