# Generated by Django 6.0.2 on 2026-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('FINANCE', 'Finance'), ('ENGINEERING', 'Engineering'), ('MARKETING', 'Marketing')], default='ENGINEERING', max_length=100),
        ),
    ]
